version: '3.4'
services:
  db:
    image: mysql:5.7.22
    ports:
    command: mysqld --default_authentication_plugin=mysql_native_password
      - 3308:3306
    networks:
      - wordpress-network
    env_file:
      - ./config/db.env 
  wordpress:
    image: wordpress:latest
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    env_file:
      - ./config/wp.env  
    ports:
      - 80:80
    networks:
      - wordpress-network
networks:
    wordpress-network:
      driver: bridge

volumes:
  db: {}